import '@/app/globals.scss'
import '@/app/generated.css'
import Header from '@/app/components/view/MainScreen/Header/Header'
import Footer from '@/app/components/view/Footer/Footer'

export const metadata = {
  title: 'Наша команда',
  description: 'Generated by create next app'
}

async function getData() {
  // noinspection JSCheckFunctionSignatures
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL_GET_SETTINGS}`,
    { next: { revalidate: 300 } }
  )

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }
  return await res.json()
}

export default async function TrainLayout({ children }) {
  const settings = await getData()
  return (
    <div>
      <Header settings={settings[0].appearance} />
      {children}
      <Footer />
    </div>
  )
}
