import '@/app/globals.scss'
import '@/app/generated.css'
import Header from '@/app/components/view/MainScreen/Header/Header'
import Footer from '@/app/components/view/Footer/Footer'
import GetSettings from '@/app/tools/getSettings'

export const metadata = {
  title: 'Наша команда',
  description: 'Generated by create next app'
}

export default async function TrainLayout({ children }) {
  const settings = await GetSettings();
  return (
    <div>
      <Header settings={settings[0].appearance} />
      {children}
      <Footer />
    </div>
  )
}
