import './globals.scss'
import './generated.css'
import Header from '@/app/components/view/MainScreen/Header/Header'
import Footer from '@/app/components/view/Footer/Footer'

export const metadata = {
  title: 'MOV.space',
  description: 'Generated by create next app'
}

async function getData() {
  // noinspection JSCheckFunctionSignatures
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL_GET_SETTINGS}`, { next: { revalidate: 300 } })

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }
  return await res.json()
}

export default async function RootLayout({ children }) {

  return (<html lang='en'>
  <head>
    <link rel='preconnect' href='https://fonts.googleapis.com' />
    <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin={'true'} />
    <link
      href='https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700;800&display=swap'
      rel='stylesheet'
    />
    <title>{metadata.title}</title>
  </head>
  <body className={'bg-black overflow-x-hidden'}>
  <main className='h-full'>
    {children}
  </main>
  </body>
  </html>)
}
